// Chat Settings menu (Phase 5). 35 options mirroring buildChatSettingsMenu
// exactly: code-concatenated emojis + live suffixes via dynamicSuffix.
// Toggles flip settings; submenu rows open existing (unmigrated) submenus.
const OPTS = [
  ['1', 'chat_enabled', '🔛', 'custom:cs_toggle_chat_enabled', 'chatEnabledState'],
  ['2', 'fuzzy_matching', '🎯', 'custom:cs_open_fuzzy', 'fuzzyModeState'],
  ['3', 'default_cooldown', '⏱️', 'custom:cs_open_cooldown', 'cooldownState'],
  ['4', 'fallback', '🌊', 'custom:cs_open_fallback', 'fallbackState'],
  ['5', 'priority_mode', '⚡', 'custom:cs_open_priority', 'priorityState'],
  ['6', 'auto_translate', '🌐', 'custom:cs_toggle_auto_translate', 'autoTranslateState'],
  ['7', 'context_awareness', '🧠', 'custom:cs_toggle_context_awareness', 'contextAwarenessState'],
  ['8', 'max_replies', '🔢', 'custom:cs_open_max_replies', 'maxRepliesState'],
  ['9', 'ignore_list', '🚫', 'custom:cs_open_ignore_list', 'ignoreListCountState'],
  ['10', 'dry_run', '🧪', 'custom:cs_toggle_dry_run', 'dryRunState'],
  ['11', 'log_matches', '📊', 'custom:cs_toggle_log_matches', 'logMatchesState'],
  ['12', 'language_filter', '🌍', 'custom:cs_open_language_filter', 'languageFilterState'],
  ['13', 'reply_delay', '⏳', 'custom:cs_open_delay_override', 'delayOverrideState'],
  ['14', 'anti_repetition', '🔁', 'custom:cs_toggle_anti_repetition', 'antiRepetitionState'],
  ['15', 'weighted_random', '⚖️', 'custom:cs_toggle_weighted_random', 'weightedRandomState'],
  ['16', 'context_awareness_enabled', '🧠', 'custom:cs_toggle_context_awareness_enabled', 'contextAwarenessEnabledState'],
  ['17', 'context_expiry', '⏱️', 'custom:cs_open_context_expiry', 'contextExpiryState'],
  ['18', 'manage_contexts', '🧠', 'custom:cs_open_context_registry', null],
  ['19', 'tone_detection', '🎭', 'custom:cs_toggle_tone_detection', 'toneDetectionState'],
  ['20', 'time_awareness', '🕒', 'custom:cs_toggle_time_awareness', 'timeAwarenessState'],
  ['21', 'tone_words', '📝', 'custom:cs_open_tone_words', null],
  ['22', 'reply_style', '🎨', 'custom:cs_toggle_reply_style', 'replyStyleState'],
  ['23', 'follow_ups', '💬', 'custom:cs_toggle_follow_ups', 'followUpsState'],
  ['24', 'follow_up_chance', '🎲', 'custom:cs_open_followup_chance', 'followUpChanceState'],
  ['25', 'ab_testing', '📊', 'custom:cs_toggle_ab_testing', 'abTestingState'],
  ['26', 'context_boost', '🎯', 'custom:cs_open_context_boost', 'contextBoostState'],
  ['27', 'rate_limit', '🚦', 'custom:cs_toggle_rate_limit', 'rateLimitState'],
  ['28', 'rate_limit_max', '🔢', 'custom:cs_open_rate_limit_max', 'rateLimitMaxState'],
  ['29', 'rate_limit_window', '⏱️', 'custom:cs_open_rate_limit_window', 'rateLimitWindowState'],
  ['30', 'snippet_depth', '🧩', 'custom:cs_open_snippet_depth', 'snippetDepthState'],
  ['31', 'typing_animation', '⌨️', 'custom:cs_toggle_typing_animation', 'typingAnimationState'],
  ['32', 'typing_targeting', '🎛️', 'custom:cs_open_typing_targeting', 'typingTargetingState'],
  ['33', 'typing_override', '🔒', 'custom:cs_toggle_typing_override', 'typingOverrideState'],
  ['34', 'typing_receipts', '📖', 'custom:cs_toggle_typing_receipts', 'typingReceiptsState'],
  ['35', 'typing_default_type', '🎙️', 'custom:cs_open_typing_default_type', 'typingDefaultTypeState']
];

const OLD_LABEL_KEY = {
  chat_enabled: 'chatSettings.optChatSystem',
  fuzzy_matching: 'chatSettings.optFuzzy',
  default_cooldown: 'chatSettings.optCooldown',
  fallback: 'chatSettings.optFallback',
  priority_mode: 'chatSettings.optPriority',
  auto_translate: 'chatSettings.optAutoTranslate',
  context_awareness: 'chatSettings.optContext',
  max_replies: 'chatSettings.optMaxReplies',
  ignore_list: 'chatSettings.optIgnoreList',
  dry_run: 'chatSettings.optDryRun',
  log_matches: 'chatSettings.optLogMatches',
  language_filter: 'chatSettings.optLanguageFilter',
  reply_delay: 'chatSettings.optDelayOverride',
  anti_repetition: 'chatSettings.optAntiRepetition',
  weighted_random: 'chatSettings.optWeightedRandom',
  context_awareness_enabled: 'chatSettings.optContextAwareness',
  context_expiry: 'chatSettings.optContextExpiry',
  manage_contexts: 'chatSettings.optManageContexts',
  tone_detection: 'chatSettings.optToneDetection',
  time_awareness: 'chatSettings.optTimeAwareness',
  tone_words: 'chatSettings.optToneWords',
  reply_style: 'chatSettings.optReplyStyle',
  follow_ups: 'chatSettings.optFollowUps',
  follow_up_chance: 'chatSettings.optFollowUpChance',
  ab_testing: 'chatSettings.optAbTesting',
  context_boost: 'chatSettings.optContextBoost',
  rate_limit: 'chatSettings.optRateLimit',
  rate_limit_max: 'chatSettings.optRateLimitMax',
  rate_limit_window: 'chatSettings.optRateLimitWindow',
  snippet_depth: 'chatSettings.optSnippetDepth',
  typing_animation: 'chatSettings.optTypingAnimation',
  typing_targeting: 'chatSettings.optTypingTargeting',
  typing_override: 'chatSettings.optTypingOverride',
  typing_receipts: 'chatSettings.optTypingReceipts',
  typing_default_type: 'chatSettings.optTypingDefaultType'
};

export default {
  id: 'chat_settings',
  headingKey: 'menu.chat_settings.heading',
  headingEmoji: null,
  standaloneCommand: '/chatsettings',
  aliases: ['/cs'],
  parent: 'chat_faq',
  backTo: 'chat_faq',
  footerKey: 'menu.chat_settings.footer',
  footerItalic: false,
  fallbackHeadingKey: 'chatSettings.title',
  fallbackFooterKey: 'admin.replyPrompt',
  transitionKey: 'chat_settings',
  sessionMenu: 'chat_settings',
  adminOnly: true,
  options: OPTS.map(([number, key, emoji, action, suffix]) => {
    const opt = { number, labelKey: `menu.chat_settings.${key}`, emoji, action, fallbackKey: OLD_LABEL_KEY[key] };
    if (suffix) opt.dynamicSuffix = suffix;
    return opt;
  })
};
