// Menu definitions register here. Imported for side effects by the
// command loader before buildMenuCommands() runs.
// Phase 3: main_menu. Phase 4: profile cluster. Phase 5: chat & FAQ cluster.
import { registerMenu } from './registry.js';
import mainMenu from './mainMenu.js';
import groupManagementMenu from './groupManagement.js';
import profileMenu from './profile/index.js';
import editProfileMenu from './profile/editProfile.js';
import preferencesMenu from './profile/preferences.js';
import myStatsMenu from './profile/myStats.js';
import messageDisplayUserMenu from './profile/messageSettings.js';
import chatFaqMenu from './chatFaq/index.js';
import chatResponsesMenu from './chatFaq/chatResponses.js';
import chatSettingsMenu from './chatFaq/chatSettings.js';
import snippetsMenu from './chatFaq/snippets.js';
import testPanelMenu from './chatFaq/testPanel.js';
import importExportMenu from './chatFaq/importExport.js';
import adminPanelMenu from './admin/index.js';
import quickActionsMenu from './admin/quickActions.js';
import broadcastMenu from './admin/broadcast.js';
import userManagementMenu from './admin/userManagement.js';
import systemSettingsMenu from './admin/systemSettings.js';
import backupRestoreMenu from './admin/backupRestore.js';
import logsMenu from './admin/logs.js';
import scheduledTasksMenu from './admin/scheduledTasks.js';
import analyticsMenu from './admin/analytics.js';
import adminSearchMenu from './admin/adminSearch.js';
import botNotificationsMenu from './admin/botNotifications.js';
import messageDisplayAdminMenu from './admin/messageDisplay.js';
import customCommandsMenu from './admin/customCommands.js';
import changelogManagerMenu from './admin/changelogManager.js';
import botContentMenu from './admin/botContent.js';
import botContentOnboardingMenu from './admin/botContentOnboarding.js';
import botContentWelcomeBackMenu from './admin/botContentWelcomeBack.js';
import botContentTimingMenu from './admin/botContentTiming.js';
import botContentLanguageMenu from './admin/botContentLanguage.js';
import botContentGroupMessagesMenu from './admin/botContentGroupMessages.js';
import settingsMenu from './settings.js';
import statisticsMenu from './statistics.js';
import tutorialMenu from './tutorial/index.js';
import { tutorialSubDefinitions } from './tutorial/subs.js';
import infoMenu from './info.js';
import { infoSubDefinitions } from './infoSubs.js';
import feedbackMenu from './feedback.js';
import faqMenu from './chatFaq/faq.js';
import faqAddMenu from './chatFaq/faqAdd.js';
import faqViewMenu from './chatFaq/faqView.js';
import faqManageMenu from './chatFaq/faqManage.js';
import faqImportExportMenu from './chatFaq/faqImportExport.js';
import faqStatsMenu from './chatFaq/faqStats.js';
import faqSearchMenu from './chatFaq/faqSearch.js';
import snippetImpexMenu from './chatFaq/snippetImpex.js';
import helpMenu from './help.js';

registerMenu(mainMenu);
registerMenu(groupManagementMenu);
registerMenu(botContentMenu);
registerMenu(botContentOnboardingMenu);
registerMenu(botContentWelcomeBackMenu);
registerMenu(botContentTimingMenu);
registerMenu(botContentLanguageMenu);
registerMenu(botContentGroupMessagesMenu);
registerMenu(profileMenu);
registerMenu(editProfileMenu);
registerMenu(preferencesMenu);
registerMenu(myStatsMenu);
registerMenu(messageDisplayUserMenu);
registerMenu(chatFaqMenu);
registerMenu(chatResponsesMenu);
registerMenu(chatSettingsMenu);
registerMenu(snippetsMenu);
registerMenu(testPanelMenu);
registerMenu(importExportMenu);
registerMenu(adminPanelMenu);
registerMenu(quickActionsMenu);
registerMenu(broadcastMenu);
registerMenu(userManagementMenu);
registerMenu(systemSettingsMenu);
registerMenu(backupRestoreMenu);
registerMenu(logsMenu);
registerMenu(scheduledTasksMenu);
registerMenu(analyticsMenu);
registerMenu(adminSearchMenu);
registerMenu(botNotificationsMenu);
registerMenu(messageDisplayAdminMenu);
registerMenu(customCommandsMenu);
registerMenu(changelogManagerMenu);
registerMenu(settingsMenu);
registerMenu(statisticsMenu);
registerMenu(tutorialMenu);
for (const def of tutorialSubDefinitions) registerMenu(def);
registerMenu(infoMenu);
for (const def of infoSubDefinitions) registerMenu(def);
registerMenu(feedbackMenu);
registerMenu(faqMenu);
registerMenu(faqAddMenu);
registerMenu(faqViewMenu);
registerMenu(faqManageMenu);
registerMenu(faqImportExportMenu);
registerMenu(faqStatsMenu);
registerMenu(faqSearchMenu);
registerMenu(snippetImpexMenu);
registerMenu(helpMenu);

// Re-export the registry API so callers import from one place.
export { registerMenu, getMenu, getAllMenus, findMenuByCommand, unregisterMenu } from './registry.js';
export { validateMenuDefinition } from './schema.js';
export { default as mainMenuDefinition } from './mainMenu.js';
export { default as groupManagementDefinition } from './groupManagement.js';
export { default as chatFaqDefinition } from './chatFaq/index.js';
export { default as chatResponsesDefinition } from './chatFaq/chatResponses.js';
export { default as chatSettingsDefinition } from './chatFaq/chatSettings.js';
export { default as snippetsDefinition } from './chatFaq/snippets.js';
export { default as testPanelDefinition } from './chatFaq/testPanel.js';
export { default as importExportDefinition } from './chatFaq/importExport.js';
export { default as adminPanelDefinition } from './admin/index.js';
export { default as quickActionsDefinition } from './admin/quickActions.js';
export { default as broadcastDefinition } from './admin/broadcast.js';
export { default as userManagementDefinition } from './admin/userManagement.js';
export { default as systemSettingsDefinition } from './admin/systemSettings.js';
export { default as backupRestoreDefinition } from './admin/backupRestore.js';
export { default as logsDefinition } from './admin/logs.js';
export { default as scheduledTasksDefinition } from './admin/scheduledTasks.js';
export { default as analyticsDefinition } from './admin/analytics.js';
export { default as adminSearchDefinition } from './admin/adminSearch.js';
export { default as botNotificationsDefinition } from './admin/botNotifications.js';
export { default as messageDisplayAdminDefinition } from './admin/messageDisplay.js';
export { default as customCommandsDefinition } from './admin/customCommands.js';
export { default as changelogManagerDefinition } from './admin/changelogManager.js';
export { default as messageDisplayUserDefinition } from './profile/messageSettings.js';
export { default as helpDefinition } from './help.js';
